---
title: "Chapter 5 The Many Variables and The Spurious Waffles"
author: "Trevor Williams"
date: "2026-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## 5.1 Spurious association

```{r 5.1}
# Load in data and standardize variables
library(rethinking)
data("WaffleDivorce")
d <- WaffleDivorce

# standardize variables
d$D <- standardize(d$Divorce)
d$M <- standardize(d$Marriage)
d$A <- standardize(d$MedianAgeMarriage)
```

Linear regression model for divorce rate ~ median age at marriage:

$$ D_{i} \sim \text{Normal}(\mu_{i}, \sigma) $$
$$ \mu_{i} = \alpha + \beta_{A}A_{i} $$
$$ \alpha \sim \text{Normal}(0, 0.2) $$
$$ \beta_{A} \sim \text{Normal}(0,0.5) $$
$$ \sigma \sim \text{Exponential}(1) $$
Where $D_{i}$ is the standardized divorce rate for State $i$ and $A_{i}$ is State $i$'s standardized median age at marriage

```{r 5.2}
# See how large one stadnard deviation of age at marriage is
sd(d$MedianAgeMarriage)
```

```{r 5.3}
# Approximate posterior distribution
m5.1 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + bA * A,
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data=d)
```

```{r 5.4}
# Simulate priors and plot lines for 2 standard deviations
set.seed(10)
prior <- extract.prior(m5.1)
mu <- link(m5.1, post=prior, data=list(A=c(-2,2)))
plot(NULL, xlim=c(-2,2), ylim=c(-2,2))
for (i in 1:50) lines( c(-2, 2), mu[i,], col=col.alpha("black", 0.4))
```

```{r 5.5}
# compute percentile interval of mean
A_seq <- seq(from = -3, to=3.2, length.out=30)
mu <- link(m5.1, data=list(A=A_seq))
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)

# plot it all
plot(D ~ A, data=d, col=rangi2)
lines(A_seq, mu.mean, lwd=2)
shade(mu.PI, A_seq)
```

```{r 5.6}
# Similar regression for divorce rate ~ marriage rate
m5.2 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + bM * M,
    a ~ dnorm(0, 0.2),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d)

```


```{r}
precis(m5.1)
```

```{r}
precis(m5.2)
```
### 5.1.1

```{r 5.7}
# Draw the first dag in the section
library(dagitty)
dag5.1 <- dagitty("dag{ A -> D; A -> M; M -> D }")
coordinates(dag5.1) <- list( x=c(A=0,D=1,M=2), y=c(A=0,D=1,M=0))
drawdag(dag5.1)

```

### 5.1.2 Testable implications

```{r 5.8}
# Display implied conditional independencies from second DAG
DMA_dag2 <- dagitty('dag{ D <- A -> M}')
impliedConditionalIndependencies(DMA_dag2)
```

```{r}
# Check conditional independencies from first DAG
DMA_dag1 <- dagitty('dag{ D <- A -> M -> D}')
impliedConditionalIndependencies(DMA_dag1)
```

### 5.1.3 Multiple regression notation

Multiple regression model for divorce, marriage, and age:

$$
















