---
title: "Chapter 7"
author: "Trevor Williams"
date: "2026-01-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## 7.1 The problem with parameters

### 7.1.1 More parameters (almost) always improve fit

```{r 7.1}
# Set up data
sppnames <- c("afarensis", "africanus", "habilis", "boisei", "rudolfensis", 
              "ergaster", "sapiens")
brainvolcc <- c(438, 452, 612, 521, 752, 871, 1350)
masskg <- c(37.0, 35.5, 34.5, 41.5, 55.5, 61.0, 53.5)
d <- data.frame(sppnames, brainvolcc, masskg)
plot(d$masskg, d$brainvolcc)
```

```{r 7.2}
# Scale and standardize data
d$mass_std <- (d$mass - mean(d$mass))/sd(d$mass)
d$brain_std <- d$brain / max(d$brain)
```

Linear model relating body mass to brain size

$$ \beta_{i} \sim \text{Normal}(\mu_{i},\sigma) $$
$$ \mu_{i} = \alpha + \beta m_{i} $$
$$ \alpha \sim \text{Normal}(0.5, 1) $$
$$ \beta \sim \text{Normal}(0,10) $$
$$ \sigma \sim \text{Log-Normal}(0, 1) $$
```{r 7.3}
# Fit the linear model
m7.1 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b*mass_std,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ),
  data=d
)
```

```{r 7.4}
# Calculate R2 from model
set.seed(12)
s <- sim(m7.1)
r <- apply(s, 2, mean) - d$brain_std
resid_var <- var2(r)
outcome_var <- var2(d$brain_std)
1 - resid_var/outcome_var

```

```{r 7.5}
# Make function to calculate R2
R2_is_bad <- function(quap_fit) {
  s <- sim(quap_fit, refresh=0)
  r <- apply(s,2,mean) - d$brain_std
  1-var2(r)/var2(d$brain_std)
}
```

Second degree model

$$ \beta_{i} \sim \text{Normal}(\mu_{i},\sigma) $$
$$ \mu_{i} = \alpha + \beta_{1} m_{i} + \beta_{2} m_{i}^2 $$
$$ \alpha \sim \text{Normal}(0.5, 1) $$
$$ \beta \sim \text{Normal}(0,10) \text{ for } j\text{ = 1..2}$$
$$ \sigma \sim \text{Log-Normal}(0, 1) $$
```{r 7.7}
# Fit second order polynomial model
m7.2 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1]*mass_std + b[2]*mass_std^2,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ),
  data=d,
  start=list(b=rep(0,2))
)
```

```{r 7.8}
# Fit third, fourth, fifth, and sixth degree models

m7.3 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
      b[3]*mass_std^3,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ),
  data=d,
  start=list(b=rep(0,3))
)

m7.4 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
      b[3]*mass_std^3 + b[4]*mass_std^4,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ),
  data=d,
  start=list(b=rep(0,4))
)

m7.5 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
      b[3]*mass_std^3 + b[4]*mass_std^4 +
      b[5]*mass_std^5,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ),
  data=d,
  start=list(b=rep(0,5))
)

```


```{r 7.9}
# Fit 6th order polynomial

m7.6 <- quap(
  alist(
    brain_std ~ dnorm(mu, 0.001),
    mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
      b[3]*mass_std^3 + b[4]*mass_std^4 +
      b[5]*mass_std^5 + b[6]*mass_std^6,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10)
  ),
  data=d,
  start=list(b=rep(0,6))
)
```


```{r 7.10}


# Plot first model
post <- extract.samples(m7.1)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.1, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.1), digits=3)))

post <- extract.samples(m7.2)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.2, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.2), digits=3)))

post <- extract.samples(m7.3)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.3, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.3), digits=3)))

post <- extract.samples(m7.4)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.4, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.4), digits=3)))

post <- extract.samples(m7.5)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.5, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.5), digits=3)))

post <- extract.samples(m7.6)
mass_seq <- seq(from=min(d$mass_std), to=max(d$mass_std), length.out=100)
l <- link(m7.6, data=list(mass_std=mass_seq))
mu <- apply(l, 2, mean)
ci <- apply(l, 2, PI)
plot(brain_std ~mass_std, data=d)
lines(mass_seq, mu)
shade(ci, mass_seq)
text(-0.75, 0.9, paste0('R2 = ', round(R2_is_bad(m7.6), digits=3)))

```

## 7.2 Entropy and accuracy

### 7.2.1 Firing the weatherperson

```{r 7.12}
# Calculate information entropy for weather with treu probabilities 0.3 and 0.7
p <- c(0.3, 0.7)
-sum(p*log(p))
```

```{r 7.13}
# Compute log-pointwise predictive-density for first model (linear model)
set.seed(1)
lppd(m7.1, n=1e4)
```

```{r 7.14}
# Compute lppd manually
set.seed(1)
logprob <- sim(m7.1, ll=TRUE, n=1e4)
n <- ncol(logprob)
ns <- nrow(logprob)
f <- function(i) log_sum_exp(logprob[,i]) - log(ns)
(lppd <- sapply(1:n, f))
```

```{r 7.15}
# Compute the log-score for each model
set.seed(1)
sapply(list(m7.1, m7.2, m7.3, m7.4, m7.5, m7.6), function(m) sum(lppd(m)))
```

```{r 7.16}
# Overthinking: Simulated training and testing
N <- 20
kseq <- 1:5
dev <- sapply(kseq, function(k) {
  print(k);
  r <- mcreplicate(1e4, sim_train_test(N=N, k=k), mc.cores=4);
  c(mean(r[1,]), mean(r[2,]), sd(r[1,]), sd(r[2,]))
  })

```


```{r 7.18}
# Plot simulations
plot(1:5, dev[1,], ylim=c(min(dev[1:2,])-5, max(dev[1:2,])+10),
     xlim=c(1, 5.1), xlab="number of parameters", ylab="deviance",
     pch=16, col=rangi2)
mtext(concat("N = ", N))
points((1:5)+0.1, dev[2,])
for (i in kseq) {
  pts_in <- dev[1, i] + c(-1, +1)*dev[3,i]
  pts_out <- dev[2,i] + c(-1,+1)*dev[4,i]
  lines( c(i,i), pts_in, col=rangi2)
  lines(c(i,i)+0.1, pts_out)
}
```

## 7.3 Golem taming: regularization

## 7.4 Predicting predictive accuracy

## 7.5 Model comparison

### 7.5.1 Model mis-selection







