---
title: "Chapter 3 Sampling the Imaginary"
author: "Trevor Williams"
date: "2025-12-20"
output: html_document
---

## Introduction

```{r 3.1}

Pr_Positive_Vampire <- 0.95
Pr_Positive_Mortal <- 0.01
Pr_Vampire <- 0.001
Pr_Positive <- Pr_Positive_Vampire * Pr_Vampire + Pr_Positive_Mortal * (1 - Pr_Vampire)
(Pr_Vampire_Positive <- Pr_Positive_Vampire*Pr_Vampire / Pr_Positive)
```

## 3.1 Sampling from a grid-approximate posterior

```{r 3.2}

# Create grid approximated posterior distribution for the globe tossing model
p_grid <- seq(from=0, to=1, length.out=1000)
prob_p <- rep(1, 1000)
prob_data <- dbinom(6, size=9, prob=p_grid)
posterior <- prob_data*prob_p
posterior <- posterior / sum(posterior)

```

```{r 3.3}

# Take 10000 samples from the posterior
samples <- sample(p_grid, prob=posterior, size=1e4, replace=TRUE)

```

```{r 3.4}

# plot samples
plot(samples)
```

```{r 3.5}

# plot density estimate
library(rethinking)

dens(samples)

```

## 3.2 Sampling to summarize

### 3.2.1 Intervals of defined boundaries

```{r 3.6}

# Get posterior probability where the proportion of water is less than 0.5
# Using grid-approximate posterior

sum(posterior[p_grid < 0.5])


```

```{r 3.7}

# Get same as above but with samples
sum(samples < 0.5)/length(samples)

```

```{r 3.8}

# Use samples to get the amount of posterior probability between 0.5 and 0.75
sum(samples > 0.5 & samples < 0.75) / length(samples)


```

### 3.2.2 Intervals of defined mass

```{r 3.9}

# Find the lower 80% posterior probability
quantile(samples, 0.8)

```

```{r 3.10}

# Find the middle 80% interval (Percentile Interval)
quantile(samples, c(0.1, 0.9))

```

```{r 3.11}

# Example with posterior with observation of 3 W in 3 tosses
p_grid <- seq(from=0, to=1, length.out=1000)
prior <- rep(1, 1000)
likelihood <- dbinom(3, size=3, prob=p_grid)
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
samples <- sample(p_grid, size=1e4, replace=TRUE, prob=posterior)
dens(samples)
```

```{r 3.12}

# Get 50% percentile compatibility interval using rethinking package
PI(samples, prob=0.5)


```

```{r 3.13}

# Get 50% highest posterior density interval (HDPI) using rethinking package
HPDI(samples, prob=0.5)

```

```{r 3.14}

# Get the maximum a posteriori (MAP) estimate (value with highest posterior probability)
# using the grid-approximate posterior
p_grid[which.max(posterior)]

```

```{r 3.15}

# Get the MAP using samples using rethinking package
chainmode(samples, adj=0.01)

```

```{r 3.16}

# Get mean and median of posterior
mean(samples)
median(samples)

```

```{r 3.17}

# Get weighted average loss from 0.5 from grid-approximate posterior
sum(posterior*abs(0.5-p_grid))

```

```{r 3.18}

# Get loss for every value in posterior
loss <- sapply(p_grid, \(d) sum(posterior*abs(d - p_grid)))

```

```{r 3.19}

# Get value that minimizes loss
p_grid[which.min(loss)]

```

## 3.3 Sampling to simulate prediction

### 3.3.1 Dummy data

```{r 3.20}
# Get probability of seeing 0, 1, or 2 Waters in two tosses of the globe
# Using p = 0.7

dbinom(0:2, size=2, prob=0.7)
```

```{r 3.21}
# Get a single dummy data observation of W for two tosses

rbinom(1, size=2, prob=0.7)
# 0 means 0 waters
# 1 means 1 water
# 2 means 2 waters
```

```{r 3.22}
# Do 10 simulations of two tosses
rbinom(10, size=2, prob=0.7)
```

```{r 3.23}
# Do 100000 simulations and compare to expected probabilities from binomial
# distribution (see code 3.20)

dummy_w <- rbinom(1e5, size=2, prob=0.7)
table(dummy_w)/length(dummy_w)
```

```{r 3.24}
# Do 100000 simulations of 9 tosses and plot histogram
dummy_w <- rbinom(1e5, size=9, prob=0.7)
simplehist(dummy_w, xlab="Dummy Water Count")
```

### 3.3.2 Model checking

#### 3.3.2.1 Did the software work?

No code in this section

#### 3.3.2.2 Is the model adequate?

```{r 3.25}
# Generate random binomial samples for single value of p

w <- rbinom(1e4, size=9, prob=0.6)
```

```{r}
# To create posterior predictive distribution use posterior for prob parameter
# This creates an simlated observations averaged over the posterior, since the 
# samples are samples from the posterior

# Create grid approximated posterior distribution for the globe tossing model
p_grid <- seq(from=0, to=1, length.out=1000)
prob_p <- rep(1, 1000)
prob_data <- dbinom(6, size=9, prob=p_grid)
posterior <- prob_data*prob_p
posterior <- posterior / sum(posterior)

# Take 10000 samples from the posterior
samples <- sample(p_grid, prob=posterior, size=1e4, replace=TRUE)

# Create posterior predictive distribution
w <- rbinom(1e4, size=9, prob=samples)
simplehist(w)
```

```{r}
simplehist(w)
```

